In [1]:
pip install scipy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: scipy in /usr/local/lib/python3.8/dist-packages (1.7.3)
Requirement already satisfied: numpy<1.23.0,>=1.16.5 in /usr/local/lib/python3.8/dist-packages (from scipy) (1.21.6)

In [2]:
pip install statsmodels

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: statsmodels in /usr/local/lib/python3.8/dist-packages (0.12.2)
Requirement already satisfied: patsy>=0.5 in /usr/local/lib/python3.8/dist-packages (from statsmodels) (0.5.3)
Requirement already satisfied: pandas>=0.21 in /usr/local/lib/python3.8/dist-packages (from statsmodels) (1.3.5)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.8/dist-packages (from statsmodels) (1.21.6)
Requirement already satisfied: scipy>=1.1 in /usr/local/lib/python3.8/dist-packages (from statsmodels) (1.7.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.21->statsmodels) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.21->statsmodels) (2022.7)
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from patsy>=0.5->statsmodels) (1.15.0)

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [16]:
!ln -s /content/drive/MyDrive/PAD_07 dan

Zadanie 1

Przeprowadź test T studenta na danych w pliku wyniki.csv

Hipoteza zerowa brzmi: nie ma istotnej różnicy w Ocenie końcowej pomiędzy uczniami i uczennicami.

Hipoteza alternatywna brzmi: istnieje istotna różnica (bez wskazania kierunku) w Ocenie końcowej pomiędzy uczniami i uczennicami.

Przyjmij significance level (alpha) na poziomie 0.05. Czy uda się odrzucić hipotezę zerową?

In [23]:
import pandas as pd
from scipy import stats

In [18]:
data = pd.read_csv('dan/wyniki.csv')
data

    plec  ocena_koncowa
0      F              6
1      F              6
2      F             10
3      F             15
4      F             10
..   ...            ...
352    M              9
353    M             16
354    M              7
355    M             10
356    M              9

[357 rows x 2 columns]

In [26]:
female = data.loc[data['plec'] == "F"]
male = data.loc[data['plec'] == "M"]
female
male

    plec  ocena_koncowa
5      M             15
6      M             11
8      M             19
9      M             15
12     M             14
..   ...            ...
352    M              9
353    M             16
354    M              7
355    M             10
356    M              9

[172 rows x 2 columns]

In [27]:
stats.ttest_ind(female["ocena_koncowa"], male["ocena_koncowa"])

Ttest_indResult(statistic=-1.9404771273257526, pvalue=0.053113174845791505)

pvalue > 0.05, więc nie możemy odrzucić hipotezy zerowej -  nie ma istotnej różnicy w Ocenie końcowej pomiędzy uczniami i uczennicami.

Zadanie 2 (2 pkt)

Korzystając z danych w pliku ZyskiFirmyX.csv stwórz model regresji liniowej i biblioteki statmodels:

•	Wyświetl wykres pokazujący zyski w czasie. 

•	Czy da się zaobserwować trend? Jaki?

•	Wyświetl podsumowanie modelu.

In [56]:
import pandas as pd
import plotly.express as px
import statsmodels.formula.api as smf
import plotly.graph_objects as go
import seaborn as sn

In [31]:
data2 = pd.read_csv('dan/ZyskiFirmyX.csv')
data2

      Rok  Zysk
0    1821  1645
1    1822   658
2    1823  1926
3    1824   865
4    1825   764
..    ...   ...
195  2016   988
196  2017   895
197  2018  -178
198  2019   543
199  2020   316

[200 rows x 2 columns]

In [39]:
fig = px.line(data2, x='Rok', y='Zysk')
fig.update_layout(title="Wykres pokazujący zyski w czasie", xaxis_title="Rok",
    yaxis_title="Zysk")
fig.show()

Na przestrzeni lat możemy zaobserwować niewielki spadek w zyskach

In [38]:
model = smf.ols(formula="Zysk ~ Rok", data=data2).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   Zysk   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.005
Method:                 Least Squares   F-statistic:                   0.09357
Date:                Fri, 27 Jan 2023   Prob (F-statistic):              0.760
Time:                        12:31:45   Log-Likelihood:                -1521.3
No. Observations:                 200   AIC:                             3047.
Df Residuals:                     198   BIC:                             3053.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   1373.8795   1150.888      1.194      0.234    -895.692    3643.452
Rok           -0.1832      0.599     -0.306      0.760      -1.364       0.998
==============================================================================
Omnibus:                        0.585   Durbin-Watson:                   2.058
Prob(Omnibus):                  0.746   Jarque-Bera (JB):                0.628
Skew:                          -0.128   Prob(JB):                        0.730
Kurtosis:                       2.900   Cond. No.                     6.39e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.39e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

Zadanie 3 (6 pkt) 

Korzystając z danych w pliku spendingscores.csv i biblioteki statmodels:

1.	stwórz model regresji liniowej, gdzie zmienną zależną jest Spending score, a zmiennymi niezależnymi pozostałe zmienne.

2.	Z modelu wyświetl:
a.	p values
b.	standard dev
c.	coefficients

3.	Sprawdź czy istnieje korelacja pomiędzy zmiennymi. Pokaż to na wykresie, np. z biblioteki plotly express.

4.	Korzystając z eliminacji wstecznej usuń najmniej istotną zmienną i jeszcze raz wyświetl model.

In [40]:
df = pd.read_csv('dan/spendingscores.csv')
df

     Gender  Age  AnnualIncome  SpendingScore
0      Male   19            15             39
1      Male   21            15             81
2    Female   20            16              6
3    Female   23            16             77
4    Female   31            17             40
..      ...  ...           ...            ...
195  Female   35           120             79
196  Female   45           126             28
197    Male   32           126             74
198    Male   32           137             18
199    Male   30           137             83

[200 rows x 4 columns]

In [50]:
replace_gender = {'Gender':{'Male':1, 'Female':0}}
df = df.replace(replace_gender)
df

     Gender  Age  AnnualIncome  SpendingScore
0         1   19            15             39
1         1   21            15             81
2         0   20            16              6
3         0   23            16             77
4         0   31            17             40
..      ...  ...           ...            ...
195       0   35           120             79
196       0   45           126             28
197       1   32           126             74
198       1   32           137             18
199       1   30           137             83

[200 rows x 4 columns]

In [51]:
model = smf.ols(formula="SpendingScore ~ Gender + Age + AnnualIncome", data=df).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          SpendingScore   R-squared:                       0.109
Model:                            OLS   Adj. R-squared:                  0.095
Method:                 Least Squares   F-statistic:                     7.960
Date:                Fri, 27 Jan 2023   Prob (F-statistic):           4.91e-05
Time:                        13:22:01   Log-Likelihood:                -922.05
No. Observations:                 200   AIC:                             1852.
Df Residuals:                     196   BIC:                             1865.
Df Model:                           3
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       73.9300      6.642     11.130      0.000      60.831      87.029
Gender          -2.0132      3.512     -0.573      0.567      -8.939       4.913
Age             -0.6004      0.125     -4.806      0.000      -0.847      -0.354
AnnualIncome     0.0079      0.066      0.119      0.905      -0.123       0.139
==============================================================================
Omnibus:                       11.059   Durbin-Watson:                   3.448
Prob(Omnibus):                  0.004   Jarque-Bera (JB):                6.033
Skew:                          -0.233   Prob(JB):                       0.0490
Kurtosis:                       2.288   Cond. No.                         291.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [52]:
print('P Values: ', model.pvalues.values)
print("Std Errs", model.bse.values)
print('Coef: ', model.params.values)

P Values:  [1.28775203e-22 5.67117187e-01 3.05517724e-06 9.05093933e-01]
Std Errs [6.64225287 3.51182541 0.12491583 0.06641961]
Coef:  [ 7.39300336e+01 -2.01323375e+00 -6.00371040e-01  7.92939510e-03]

In [61]:
px.imshow(df.corr(), color_continuous_scale='Agsunset', title="Korelacja zmiennych")

Usuwam zmienną Gender, ponieważ jej p value jest największe.

In [64]:
model = smf.ols(formula="SpendingScore ~ Age + AnnualIncome", data=df).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          SpendingScore   R-squared:                       0.107
Model:                            OLS   Adj. R-squared:                  0.098
Method:                 Least Squares   F-statistic:                     11.82
Date:                Fri, 27 Jan 2023   Prob (F-statistic):           1.42e-05
Time:                        13:44:49   Log-Likelihood:                -922.21
No. Observations:                 200   AIC:                             1850.
Df Residuals:                     197   BIC:                             1860.
Df Model:                           2
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       73.3479      6.553     11.193      0.000      60.425      86.271
Age             -0.6048      0.124     -4.859      0.000      -0.850      -0.359
AnnualIncome     0.0057      0.066      0.087      0.931      -0.125       0.136
==============================================================================
Omnibus:                       10.159   Durbin-Watson:                   3.452
Prob(Omnibus):                  0.006   Jarque-Bera (JB):                6.026
Skew:                          -0.254   Prob(JB):                       0.0491
Kurtosis:                       2.318   Cond. No.                         286.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.